### ISSUE TITLE
Correctly handle incorrect system URLs

### ISSUE THREAD

**Issue by thejflo** [mrusme/neonmodem#39]
Hi, I'm a bit of a noob and I can't seem to get neonmodem working - neither by using the binary nor by building it myself. I'd appreciate any help!

```
OS: Pop!_OS 22.04 LTS
KERNEL: Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux
```

I've installed the latest stable Go to /usr/local/go after finding the upstream Go packages for my distro are too old.

The **make** command builds the binary successfully without error.

After building from Source:

```
~/Documents/dev/neonmodem$ ./neonmodem 
panic: Error(s) loading system(s)

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.glob..func1(0x1781720?, {0xeae714?, 0x0?, 0x0?})
	/home/user/Documents/dev/neonmodem/cmd/root.go:128 +0x267
github.com/spf13/cobra.(*Command).execute(0x1781720, {0xc000098200, 0x0, 0x0})
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1781720)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute(0xc0000061a0?)
	/home/user/Documents/dev/neonmodem/cmd/root.go:141 +0x3e
main.main()
	/home/user/Documents/dev/neonmodem/neonmodem.go:13 +0x25
```

Attempting to use Binary:

```
~/bin$ neonmodem 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd45616]

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.loadSystems(0xc000454780)
	/home/runner/work/neonmodem/neonmodem/cmd/root.go:105 +0xb6
github.com/mrusme/neonmodem/cmd.glob..func1(0x1770140?, {0xe9628b?, 0x0?, 0x0?})
	/home/runner/work/neonmodem/neonmodem/cmd/root.go:122 +0xdc
github.com/spf13/cobra.(*Command).execute(0x1770140, {0xc000022230, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1770140)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute(0xc0000061a0?)
	/home/runner/work/neonmodem/neonmodem/cmd/root.go:134 +0x3e
main.main()
	/home/runner/work/neonmodem/neonmodem/neonmodem.go:13 +0x25
```

**Comment by BreadMakesYouFat** [comment]
I can reproduce this error when I set password incorrectly for lemmy. Might be worth checking or re-generating your config file.

**Comment by thejflo** [comment]
Ahhh good idea, but it seems it was because I hadn't put "https://" on the
URL.

**Comment by mrusme** [comment]
Hey thanks, I've updated the issue's title so that we know what needs to be done!

**Comment by dtantono** [comment]
Yeah, I got same issue with lemmy.world for first sign in
![Uploading image.png…]()

**Comment by mrusme** [comment]
This was fixed within https://github.com/mrusme/neonmodem/commit/b3b41c07952a666532072743c992472b5a8a5038 by allowing NMO to launch even when individual systems fail. Details on why something failed can be checked for in `~/.cache/neonmodem.log`.
