### ISSUE TITLE
400 Bad Request: missing_totp_token

### ISSUE THREAD

**Issue by mhzawadi** [mrusme/neonmodem#43]
Morning my good devs,

I have just downloaded the latest Mac arm64 build and connected it to my lemmy instance (https://lemmy.horwood.cloud/), but on starting neonmodem I get an error.

```
panic: Error(s) loading system(s)

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.glob..func1(0x101edd0c0?, {0x1014b7db4?, 0x1?, 0x1?})
	/home/runner/work/neonmodem/neonmodem/cmd/root.go:128 +0x1ec
github.com/spf13/cobra.(*Command).execute(0x101edd0c0, {0x1400001e050, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x101edd0c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute(0x1018206e0?)
	/home/runner/work/neonmodem/neonmodem/cmd/root.go:141 +0x58
main.main()
	/home/runner/work/neonmodem/neonmodem/neonmodem.go:13 +0x24
```

running with debug is the same, but a quick look in the logs show this is a login issue.

```
{"level":"error","ts":1688973078.467069,"caller":"cmd/root.go:97","msg":"error loading system: 400 Bad Request: missing_totp_token","stacktrace":"github.com/mrusme/neonmodem/cmd.loadSystems\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:97\ngithub.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:123\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
{"level":"error","ts":1688973078.467602,"caller":"cmd/root.go:126","msg":"400 Bad Request: missing_totp_token","stacktrace":"github.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:126\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
{"level":"error","ts":1688973129.346163,"caller":"cmd/root.go:97","msg":"error loading system: 400 Bad Request: missing_totp_token","stacktrace":"github.com/mrusme/neonmodem/cmd.loadSystems\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:97\ngithub.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:123\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
{"level":"error","ts":1688973129.346896,"caller":"cmd/root.go:126","msg":"400 Bad Request: missing_totp_token","stacktrace":"github.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:126\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
2023-07-10T08:12:36.739+0100    DEBUG   cmd/root.go:93  loading system of type lemmy ...
2023-07-10T08:12:37.224+0100    ERROR   cmd/root.go:97  error loading system: 400 Bad Request: missing_totp_token
github.com/mrusme/neonmodem/cmd.loadSystems
    /home/runner/work/neonmodem/neonmodem/cmd/root.go:97
github.com/mrusme/neonmodem/cmd.glob..func1
    /home/runner/work/neonmodem/neonmodem/cmd/root.go:123
github.com/spf13/cobra.(*Command).execute
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute
    /home/runner/work/neonmodem/neonmodem/cmd/root.go:141
main.main
    /home/runner/work/neonmodem/neonmodem/neonmodem.go:13
runtime.main
    /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
2023-07-10T08:12:37.224+0100    ERROR   cmd/root.go:126 400 Bad Request: missing_totp_token
github.com/mrusme/neonmodem/cmd.glob..func1
    /home/runner/work/neonmodem/neonmodem/cmd/root.go:126
github.com/spf13/cobra.(*Command).execute
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute
    /home/runner/work/neonmodem/neonmodem/cmd/root.go:141
main.main
    /home/runner/work/neonmodem/neonmodem/neonmodem.go:13
runtime.main
    /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
```

**Comment by mrusme** [comment]
Hey there, does your instance utilize second factor authentication? In that case this might be the issue, since I haven't yet explicitly taken a look on how this needs to be handled. In case you do use 2FA, you might try to temporarily disable it and see whether you still get the error.

**Comment by mrusme** [comment]
Closing this as I assume that it was the reason why login wasn't working. Neon Modem does not yet support 2FA for logins.
