### ISSUE TITLE
Error with lemmy connection and totp

### ISSUE THREAD

**Issue by vsis** [mrusme/neonmodem#66]
I have a lemmy account with TOTP 2FA and I'm running neonmodem-1.0.5-1.

When I try to open neonmodem I see this error:

```
$ neonmodem --debug
panic: Error(s) loading system(s)

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.init.func1(0xc000151300?, {0x5d05c4125fa6?, 0x4?, 0x5d05c4125faa?})
	github.com/mrusme/neonmodem/cmd/root.go:128 +0x20e
github.com/spf13/cobra.(*Command).execute(0x5d05c4b58e80, {0xc000036050, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x5d05c4b58e80)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mrusme/neonmodem/cmd.Execute(...)
	github.com/mrusme/neonmodem/cmd/root.go:141
main.main()
	github.com/mrusme/neonmodem/neonmodem.go:13 +0x45
```

Logs in `.cache/neonmodem.log` says:

```
{"level":"error","ts":1728680781.7349668,"caller":"cmd/root.go:97","msg":"error loading system: Post \"https://feddit.cl/api/v3/user/login\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","stacktrace":"github.com/mrusme/neonmodem/cmd.loadSystems\n\tgithub.com/mrusme/neonmodem/cmd/root.go:97\ngithub.com/mrusme/neonmodem/cmd.init.func1\n\tgithub.com/mrusme/neonmodem/cmd/root.go:123\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/mrusme/neonmodem/cmd.Execute\n\tgithub.com/mrusme/neonmodem/cmd/root.go:141\nmain.main\n\tgithub.com/mrusme/neonmodem/neonmodem.go:13\nruntime.main\n\truntime/proc.go:272"}
{"level":"error","ts":1728680781.7351224,"caller":"cmd/root.go:126","msg":"Post \"https://feddit.cl/api/v3/user/login\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","stacktrace":"github.com/mrusme/neonmodem/cmd.init.func1\n\tgithub.com/mrusme/neonmodem/cmd/root.go:126\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/mrusme/neonmodem/cmd.Execute\n\tgithub.com/mrusme/neonmodem/cmd/root.go:141\nmain.main\n\tgithub.com/mrusme/neonmodem/neonmodem.go:13\nruntime.main\n\truntime/proc.go:272"}
2024-10-11T23:07:16.398+0200	DEBUG	cmd/root.go:93	loading system of type lemmy ...
2024-10-11T23:07:18.566+0200	ERROR	cmd/root.go:97	error loading system: 400 Bad Request: missing_totp_token
github.com/mrusme/neonmodem/cmd.loadSystems
	github.com/mrusme/neonmodem/cmd/root.go:97
github.com/mrusme/neonmodem/cmd.init.func1
	github.com/mrusme/neonmodem/cmd/root.go:123
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:987
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mrusme/neonmodem/cmd.Execute
	github.com/mrusme/neonmodem/cmd/root.go:141
main.main
	github.com/mrusme/neonmodem/neonmodem.go:13
runtime.main
	runtime/proc.go:272
2024-10-11T23:07:18.566+0200	ERROR	cmd/root.go:126	400 Bad Request: missing_totp_token
github.com/mrusme/neonmodem/cmd.init.func1
	github.com/mrusme/neonmodem/cmd/root.go:126
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:987
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mrusme/neonmodem/cmd.Execute
	github.com/mrusme/neonmodem/cmd/root.go:141
main.main
	github.com/mrusme/neonmodem/neonmodem.go:13
runtime.main
	runtime/proc.go:272
```

The key part of the logs seems to be:

```
ERROR	cmd/root.go:97	error loading system: 400 Bad Request: missing_totp_token
```

My system is:

```
$ uname -a
Linux almendra 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux
```

**Comment by mrusme** [comment]
Check [this](https://github.com/mrusme/neonmodem/issues/43#issuecomment-1630899689), 2FA/TOTP is not yet supported. Happy to accept PRs for that, though!
